### ISSUE TITLE
Setting console colours internally is inefficient

### ISSUE THREAD

**Issue by caeserlettuce** [caeserlettuce/dapug-console#22]
Basically I need to set it so there's only one function called setColour() where it's like this essentially:

```javascript
setColour({
"text": "#ffffff",
"background": "#000000", 
"accent": "#1e1e1e"
});
```

**Comment by 18gallons** [comment]
i made one of these for the beans branch, pending review.

**Comment by caeserlettuce** [comment]
yeah caffy fixed it
