### ISSUE TITLE
change the cursor from a blink line to the filled in ascii character because it looks nicer

### ISSUE THREAD

**Issue by 18gallons** [caeserlettuce/dapug-console#46]

**Comment by 18gallons** [comment]
blinky*

**Comment by caeserlettuce** [comment]
i don't know if i can do that, i could see though

i need to find the code for that in the first place

**Comment by caeserlettuce** [comment]
cause the actual character is some fancy css trick i think if i remember correctly

**Comment by caeserlettuce** [comment]
Im trying to find where that original code is and I'm having trouble but I found this https://www.amitmerchant.com/simple-blinking-cursor-animation-using-css/#:~:text=The%20first%20and%20foremost%20thing,after%20pseudo%2Delement%20like%20so.

**Comment by caeserlettuce** [comment]
so this is funny

**Comment by caeserlettuce** [comment]
There IS no code for the cursor. Because it's the default blinky cursor.

**Comment by caeserlettuce** [comment]
https://stackoverflow.com/questions/2897155/get-cursor-position-in-characters-within-a-text-input-field

could use this, make another element that is positioned in the same spot, and then yknow

but then that may cause issues when it comes to overflow when you have a really long command and it scrolls, but I'll figure it out I hope

**Comment by caeserlettuce** [comment]
update it's literally almost impossible :sob:
