### ISSUE TITLE
add a command where you can change the console font

### ISSUE THREAD

**Issue by caeserlettuce** [caeserlettuce/dapug-console#48]
either change it to a built-in font, or you can provide your own font via link

**Comment by 18gallons** [comment]
ah yes set it to a variably-spaced font that'll look nice

**Comment by caeserlettuce** [comment]
shush shush shush shush that's for the user to figure out

**Comment by caeserlettuce** [comment]
ok this isnt really possible so nevermind


well it is possile, but it's annoying cause i have to mess with css, so its bad
