### ISSUE TITLE
console could make lil noises 

### ISSUE THREAD

**Issue by caeserlettuce** [caeserlettuce/dapug-console#99]
like an ambient computer noise always in the background, some sounds of reading and writing, a startup noise for startup

**Comment by 18gallons** [comment]
you could use this as an excuse for buffering the songs, during that split second while they load

**Comment by 18gallons** [comment]
by that i mean you can do some floppy disk reading noises for a second before the song starts, to ensure you have the song ready in time

**Comment by caeserlettuce** [comment]
bleep blop sounds are kinda annoying
